### ISSUE TITLE
Protect develop and master branch

### ISSUE THREAD

**Issue by fgypas** [fgypas/panoptes#45]
Make sure that the branch **develop** and the branch **master** is protected. Noone should be able to push directly there.

**Comment by agardelakos** [comment]
After the initial investigation, we concluded that we need to change the owner of this project into an organisation. This will provide us the capability not only to protect the develop & master branches but also to make teams for the potential collaborators. The new project can be found here: https://github.com/panoptes-organization/panoptes

**Comment by fgypas** [comment]
Great. Can we also move the open issues and the projects there?

**Comment by agardelakos** [comment]
I am afraid not. According to this link https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository.

> You can't transfer an issue from a private repository to a public repository.

**Comment by fgypas** [comment]
OK, I manually moved all open issues here:

https://github.com/panoptes-organization/panoptes/issues
